<script lang="ts">
  import { fade } from 'svelte/transition';
  import { onMount } from 'svelte';
  import { Loader2, Menu, X } from '@lucide/svelte';
  import { loadOpenApi, groupOperationsByTag, type OpenApiOperation, type OpenApiSpec } from './lib/openapi';
  import EndpointList from './lib/components/EndpointList.svelte';
  import EndpointDetail from './lib/components/EndpointDetail.svelte';

  let spec = $state<OpenApiSpec | null>(null);
  let error = $state<string | null>(null);
  let selected = $state<OpenApiOperation | null>(null);
  let loaded = $state(false);
  let mobileMenuOpen = $state(false);

  const groups = $derived(spec ? groupOperationsByTag(spec) : []);

  onMount(() => {
    loadOpenApi()
      .then((s) => {
        spec = s;
        loaded = true;
        // Select first operation by default
        if (groups.length > 0 && groups[0].operations.length > 0) {
          selected = groups[0].operations[0];
        }
      })
      .catch((e) => {
        error = e instanceof Error ? e.message : String(e);
        loaded = true;
      });
  });

  $effect(() => {
    if (spec && groups.length > 0 && !selected) {
      selected = groups[0].operations[0];
    }
  });

  function handleSelect(operation: OpenApiOperation) {
    selected = operation;
    mobileMenuOpen = false;
  }
</script>

<div class="h-svh flex flex-col bg-surface">
  <header class="shrink-0 border-b border-border bg-surface/80 backdrop-blur z-10">
    <div class="flex items-center justify-between px-5 py-3">
      <div class="flex items-center gap-3">
        <button
          class="md:hidden inline-flex items-center justify-center w-8 h-8 rounded-lg border border-border text-text-heading hover:bg-surface-elevated"
          onclick={() => (mobileMenuOpen = !mobileMenuOpen)}
          aria-label="Toggle menu"
        >
          {#if mobileMenuOpen}
            <X class="w-4 h-4" />
          {:else}
            <Menu class="w-4 h-4" />
          {/if}
        </button>
        <div class="w-8 h-8 rounded-lg bg-accent flex items-center justify-center text-white font-bold text-sm">API</div>
        <div>
          <h1 class="text-base font-semibold text-text-heading leading-tight">{spec?.info.title ?? 'API Reference'}</h1>
          {#if spec}
            <div class="text-xs text-text-muted">{spec.info.version} · {groups.reduce((n, g) => n + g.operations.length, 0)} endpoints</div>
          {/if}
        </div>
      </div>
      <div class="text-xs text-text-muted">
        Generated by gswr
      </div>
    </div>
  </header>

  {#if !loaded}
    <div class="flex-1 flex items-center justify-center">
      <Loader2 class="w-6 h-6 text-accent animate-spin" />
    </div>
  {:else if error}
    <div class="flex-1 flex items-center justify-center p-8">
      <div class="max-w-md text-center">
        <div class="text-delete font-medium mb-2">Failed to load OpenAPI spec</div>
        <div class="text-sm text-text-muted">{error}</div>
      </div>
    </div>
  {:else if spec}
    <div class="flex-1 flex overflow-hidden">
      {#if mobileMenuOpen}
        <div
          class="fixed inset-0 z-20 bg-black/20 md:hidden"
          onclick={() => (mobileMenuOpen = false)}
          role="presentation"
        ></div>
      {/if}
      <aside
        class="absolute md:relative z-30 w-80 h-full shrink-0 border-r border-border bg-surface-elevated overflow-hidden transition-transform duration-200 ease-out {mobileMenuOpen
          ? 'translate-x-0'
          : '-translate-x-full md:translate-x-0'}"
      >
        <EndpointList {groups} {selected} onSelect={handleSelect} />
      </aside>

      <main class="flex-1 overflow-y-auto">
        <div class="max-w-4xl mx-auto px-6 py-8">
          {#if selected}
            {#key selected}
              <div in:fade={{ duration: 150 }}>
                <EndpointDetail operation={selected} {spec} />
              </div>
            {/key}
          {:else}
            <div class="text-center py-20 text-text-muted">Select an endpoint to view details.</div>
          {/if}
        </div>
      </main>
    </div>
  {/if}
</div>
